language: java
env:
  global:
    - secure: "RyOQ8fUxX656+KGrZBj0tEfcD+IuC5dfdTVkfpn/ZwSXEi7v1IgJhHd6DZTOk67GbO0Gop8PFa//IMxNWtPo7nxhgvl07PNDzjQggGWI/oCfPF/9/cQUUFs7ViTTDNWLV0a3ph5d+S3uLyYyONDpgdozJi2gtiE66HK6GznbXlwb1ZxRSETteFf+dvKvEND3AzJu7EsLOpyBNuEoGBFYuKCL0qCRC0HCMxnv3+8avg7HKCQzObKbuzWWupB05RMI1bY99JcK7sTZimtQDfQPQIltKaiYDwHS3To4Ytsshg1xmbBhsq1KGEnZ/c9uAeqIQO/fHYeJ34DnUJLP2XzzYFBABg7TZrtu4yVunt/OMlFjIuyn+27q4H3NJL7kGtg7GxSAkLaNNkjSaPU0stH2Wn8j1I5LNnQOGMSzMOo3oonNZozbk7njMjn4spMxC4B2Jrestx2uGzDpdNA3XIze7ZjEJ9vk7I3jsvG0VADPYZ+DkO5AqzPYYfUWuyVm82lKdHpGcpz7VJ09kdnbDBL7wv+dDW8tqI0arrgrUk9d2AJuzitLPUs5fbjTRc4DXmMFAcTuvjOyYh+nxskkqLfd7wWv2QCRJgsdvoixyj11jj3wC/061WmKmazll2oNxAgy+Jbhg6wTYPHT/L6bIMwdbOizhQl4JetCHrVmpgofYCY="
    - secure: "IrUJ+CMf1EG3qcFHvxySbOQoSLmJN52k+gou8ywMA2nQhX75Jhl4mcSSjHN/i8nwvs6alJ3Kxx/y6tYD2KfHbw+sCocY3zYY6pMJ+OVNPBmng/aFJNAXeaAXOC+ExEZH35FLmDYTSeejLY8XJ6nEc2m3jHTIuV/A49PbQ95RTWfEJpb23R7q0YbHiXArjjQagmjE81baoA43aYPpK+gvA0rD5BrO6Cy3mjUz/tjg2tTVupQl9KDhkK4lTjlGTVxlrXC2TFNs7m10CU0J/kTVnoiLZ83Y6fOR3RZafFt0h2yqGok384x5Zv7lEAnrg1DthmZ/UC9JszM+2FnYDH0L4Sj/45iwKKK48WzxnoYEuHQf9wxmIOLqpCMLKy/mo76gb/e7NRHbGDPc3qd+rQuYK8L1wJQIUSwx0/4mA72stmhADu0daMN0Nw14lxZy2FeRJUEcH5I2ddIMwxunA6X/qsllGUasCd1tMW8rGSGsD9b4rUxTNYrO6qWa4PCCS/Z701cNHNbw1quZzsWyG1KU9Kzhr8TzP7OO0PU4J3TV5mfiida4ISI7Uo0Yg4SHS+eY72gwQ5TScSXqMrZtdcaakwhFcGN2674b34lppspPfARaeGgRL0UYv7UdMjeg0XM9wVLqklPDIqXTFTXoYZJ+s8xocYB8ckOZxNInYA/hlng="
    - secure: "S7KiIbyu+MUODEzpxozf/4a46F4XA/UqXPHPQldvb51BblEAnGuId3pAqfuDiDSdeN2t8HE2QF+gKYCL89DIx7rW3i+OFGJFmgkU+Axx0VeOp0y3/wzWNHhhcK4/eySSospVsJFvUC28nhwkMnbH+59KnWwAKoX1bGsLYkD3JNd9q5vuKvF22PYA1PMF5Og88XNjURvXGvJRjBJWmLz/bm4agj8N2/RGyoupEQMLx39rCfz2sVzNLsCvzRsE+C6VuQmgyyw+9bBliLLjYlaxTmQnoCnjLjKycjz9mt/3LvBS6BiDXHKEdqc/hpfQF5Gk2Hmy+aCnWhwDFKSXtc2IO6Qp1Ei3JNAF6IXfI5l5vAlfPSBMWNiddj+9+/kOE/b6GEbsGUZSJxjxfj2JPG2KJ6lrFOKWb7zCabUZKGGCnpL5+gT5vcqEMrEmQd1qiADJ7XBEwJr6IZLEnJH1GKMwZE2t+UU61wcaHK4ikHhsApMSkuD1ECgpOBFMWh63UdTrWDY/H7fzW487BZbPPwMF6p8vpzleaisDMDy2vH3QC5lftnGdCR2YlCU2u/9TqhmJz5FhLRyyG7e7pSJWknM5o2xHMYC2NfOhJgf595ZBsyFlh3Ffo22q/jPHTzNT4YtHxWrYYC5+ctipvHfZaxVtEsaNjkK9pbiY0YH/UJOTTUc="
    - secure: "LIq2TWX6b+/n0A3iY+lrFB1ZY7ejULSrWiHI2f7M5v1ItKg3k/uaNHpFq4RA7KQX7BP3bwIkJfxXxndHSrMGCNjzhNL+etqf6prBGJM1nkaWy+8dC7HDGIwmtKCXHj1f978hOLJO7kOfFHeyDsrVoHfZm0dpbg9jdvgnTFQSoDqN69CqJfFWb/i0F/Tut+QKs8RmxPpd16uP7hkPt1IMkXV6m9iysXNqztSe0HS2358b9tS0EDKYio+SF36ki5EEnvuLOqn5p6jMoAK1VXi0TOWAQak42WrNI6OEj0mqYwGdRgAV2PyxSkLgdvfBDt6J4IGRjJ437exuIFsrPsoRByT2lC83koQjAX+origfUQir8A6a8+qgdjHE8hTYry79PXOJkNP5FlamDct5W6Vr6gxJiWeUYiUz3Bs42lLAbwQfe3/jtOtVZY/4E0CxMovQf2NGL3BeGQr1hPsreHyyXomj71yViBfLqoW00rYy3Q4vi8ExiJ6YpIeRrmUYdn6aFufNro9u9SWdLVobTRFiwsDv+BW/sB+RUNZyRK7WSC5YNEMcFQgHuqJaQc4iZiqNZqqK7wvjCNBYQiCnreL02DPbsAsnsdwQLWfL2RFP1bFR5d17PqfWn21TYZfoRH+ruA8LYlatLjFAzwKwYKbSNF+Fn02j46XXzeE37Jp7Nxg="

sudo: required

install: true

services:
  - docker

cache:
  directories:
    - '$HOME/.m2/repository'

script:
- mvn verify && bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: .travis/deploy.sh
    on:
      branch: master
  - provider: script
    script: .travis/release.sh
    on:
      tags: true