language: java
env:
  global:
    - secure: "RyOQ8fUxX656+KGrZBj0tEfcD+IuC5dfdTVkfpn/ZwSXEi7v1IgJhHd6DZTOk67GbO0Gop8PFa//IMxNWtPo7nxhgvl07PNDzjQggGWI/oCfPF/9/cQUUFs7ViTTDNWLV0a3ph5d+S3uLyYyONDpgdozJi2gtiE66HK6GznbXlwb1ZxRSETteFf+dvKvEND3AzJu7EsLOpyBNuEoGBFYuKCL0qCRC0HCMxnv3+8avg7HKCQzObKbuzWWupB05RMI1bY99JcK7sTZimtQDfQPQIltKaiYDwHS3To4Ytsshg1xmbBhsq1KGEnZ/c9uAeqIQO/fHYeJ34DnUJLP2XzzYFBABg7TZrtu4yVunt/OMlFjIuyn+27q4H3NJL7kGtg7GxSAkLaNNkjSaPU0stH2Wn8j1I5LNnQOGMSzMOo3oonNZozbk7njMjn4spMxC4B2Jrestx2uGzDpdNA3XIze7ZjEJ9vk7I3jsvG0VADPYZ+DkO5AqzPYYfUWuyVm82lKdHpGcpz7VJ09kdnbDBL7wv+dDW8tqI0arrgrUk9d2AJuzitLPUs5fbjTRc4DXmMFAcTuvjOyYh+nxskkqLfd7wWv2QCRJgsdvoixyj11jj3wC/061WmKmazll2oNxAgy+Jbhg6wTYPHT/L6bIMwdbOizhQl4JetCHrVmpgofYCY="
    - secure: "IrUJ+CMf1EG3qcFHvxySbOQoSLmJN52k+gou8ywMA2nQhX75Jhl4mcSSjHN/i8nwvs6alJ3Kxx/y6tYD2KfHbw+sCocY3zYY6pMJ+OVNPBmng/aFJNAXeaAXOC+ExEZH35FLmDYTSeejLY8XJ6nEc2m3jHTIuV/A49PbQ95RTWfEJpb23R7q0YbHiXArjjQagmjE81baoA43aYPpK+gvA0rD5BrO6Cy3mjUz/tjg2tTVupQl9KDhkK4lTjlGTVxlrXC2TFNs7m10CU0J/kTVnoiLZ83Y6fOR3RZafFt0h2yqGok384x5Zv7lEAnrg1DthmZ/UC9JszM+2FnYDH0L4Sj/45iwKKK48WzxnoYEuHQf9wxmIOLqpCMLKy/mo76gb/e7NRHbGDPc3qd+rQuYK8L1wJQIUSwx0/4mA72stmhADu0daMN0Nw14lxZy2FeRJUEcH5I2ddIMwxunA6X/qsllGUasCd1tMW8rGSGsD9b4rUxTNYrO6qWa4PCCS/Z701cNHNbw1quZzsWyG1KU9Kzhr8TzP7OO0PU4J3TV5mfiida4ISI7Uo0Yg4SHS+eY72gwQ5TScSXqMrZtdcaakwhFcGN2674b34lppspPfARaeGgRL0UYv7UdMjeg0XM9wVLqklPDIqXTFTXoYZJ+s8xocYB8ckOZxNInYA/hlng="
    - secure: "qTmZ/DMmIrf+lorFavrc18aHIZvar2iEUHpJQh70+f3abli6Wl5BW+MNb1j01OxFWFFLO6Y4uLzs6NyFe20/OMD3PiGicmqk1gDvKtSp6l4QKMhfFAD5eAD4o6phiWmxuYVO33njNquhG8FKj8ddaNPfiXS4ViajHdE04KeotrPCaqhNthJO42YL59oOmwT++PtCro6/CwXmKWFaPyNQ+GseJ1OKe6KiKTOW1Au0BhQLyT8vfpE20gci1wcGXr3AjjqQ6Dp+BWrT0+YXopffOJo+tL5fkLdV/gja3kwrgJJrQWzbF6C5mqJ0btPxqUPY4pgjDGDsfXn2uaojVcNabv8W3kh5YybVMAOJGN91xI4etv2nLaPQWB/AbP7zZ0QTbPWYieuOjDnnL1tmZwIT7iXbGfkz3BHcG4UtLz4XUIyvE/ICUTUZwC8OHctqEC84y38z2HiB9ErIbVDtv+eXqDNBlKZXrj9wRCqz+eSkYrnwabVHN76sVePOZmnlO/MNQ8cTT5Rug69YJqNODnTmGFHNPe9tJwuhxJyzhJkXtF+TRi1wsG+eBMUBtRUgD1a28jNlZC/hsQ/OlwSMUs2oimda0NPZiqdX2nBblTrN1jCuauppMRZy9TlT6p6oMWENrV8haxwqMIPsV/Ym2rYLGHkxBeYggf5i1/y/3AzVHB4="
    - secure: "DLRfMtS/WkAnHpTUyL79XQ2nH2Jf/DcRV3GqAc0bouyfudgzC7mYUO11Wd/8DldxNE8Z5+UtjnfMEjnXy2DmKQU2rJvenGe6VCKjkUWX4yk8H1GVyEug3eeGBVL4GoXxYggG75nkvWIUq92ngoFUUTQPU2MULmNDjNywfpKyQ/PKjrtj5y01sYpy0nWDblUkAX+5CREcEyezjehREtWKAnSKOQfpDdeKRG0zdTx1igh8kL1YEwUxJTgLBmzs9niUwpFUAOummwvb/IZuOBjLXVylAEzr8MDRCD/b67GHJnw1wxXNGgwfsKuNURS0qb8JBZE67Ik0TZdHLAa+AxQ8np/KfR9NmLqmz4p0Y5gxehve6hfonXql6kunOObX9s+6wILJKsBMs7yRtkZaOO0MZSjXbYuVN7fs0RFVzOqCdUmyXyDS+uLwIpzQ+gTLJGgQT31JrvljCePmM2Enkza4Vlh4nUb5aMahjTfQhWGQqWf1FDf4SLzt1IQzBLNvBNfZsnKDOwlaRFVrco+8JO7818xPHPhjgJT4VdR966GewEyN2CGNihSMiX/YL/Jyg/cThDx9HeoCQUDsKtm5vWrsYQxrNxxyO8zdVIlfKZiUbeGhCLHVqsQ/BY1hLpidQg9icI1TgTxKzDaG1wm9/8PPzbQN4HyM9ZY1KNRN/a9Dim4="

sudo: required

install: true

services:
  - docker

cache:
  directories:
    - '$HOME/.m2/repository'

script:
- mvn -V --batch-mode -Dstyle.color=always clean verify && bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: .travis/deploy.sh
    on:
      branch: master
  - provider: script
    script: .travis/release.sh
    on:
      tags: true